### ISSUE TITLE
Incorrect Information

### ISSUE THREAD

**Issue by Gonsan78** [EDSM-NET/FrontEnd#170] opened 2018-06-13 12:49 UTC
[https://www.edsm.net/en/system/id/20384254/name/Pyurks+HC-J+d10-18](url)

La información proporcionada por la página NO ES CIERTA. CMDR Daesglarr NO DESCUBRIÓ ese sistema para EDSM. Corrijan los datos por favor.

The information provided by the page IS NOT TRUE. CMDR Daesglarr did not discover that system for EDSM. Correct the data please.

POI submission CMDR Gonsan78 - ASP Explorer (Z4RK0V)
Type: Stellar POI (Stellar Features) Name: Twin Stars Galaxy map reference: PYURKS HC-J D10-18 (UPDATE: Already included in the EDSM database!)
Description: Curious system with 6 stars in which 2 of them are literally stuck together (see photos) according to their position in the orbit.

**Comment by AnthorNet** [comment] 2018-06-13 13:00
First discovery are based on flight logs submitted only.
If another flight log is submitted before, the first discovery will update.

**Comment by Gonsan78** [comment] 2018-06-13 13:16
https://forums.frontier.co.uk/showthread.php/116450-Information-The-Galactic-Mapping-Project-amp-Expedition-Hub?p=6264604&viewfull=1#post6264604

**Comment by AnthorNet** [comment] 2018-06-13 13:40
This does not interfere with the Galactic Mapping description.
First discovery are based on flight logs. Send your journal into EDSM and it will update.

**Comment by Gonsan78** [comment] 2018-06-13 14:08
How do I submit a new system for the Galactic Mapping Project?

Just write a post in the Frontier Forum here:
https://forums.frontier.co.uk/showthread.php/116450-Information-The-Galactic-Mapping-Project-Expedition-Hub

I do not see nothing about sending the Journal anywhere in th FAQ´s on your
Web.
Anyway, tell me how to send the Journal from a PS4 and I'll do it right
away.

Best Regards

**Comment by AnthorNet** [comment] 2018-06-13 14:17
Other functionality aren't connected.

First discovery are for flight logs which is a PC only features.

Galactic description are handled on the forum post, but do not update the first discovery part.

**Comment by Gonsan78** [comment] 2018-06-13 14:26
In summary: that it is not true what the page says, no matter what is not
discovered on PC and what others discover is only awarded to your 4
friends... Right?
OK, then I demand that my description of the system that I discover will be
immediately deleted from your website as well as my photos.

If you want photos of the systems that you have not discovered to fill your
web, I recommend that you travel there and do them yourselves...

Best Regards

**Comment by AnthorNet** [comment] 2018-06-13 14:34
No need to be rude or agreesive...
First we are not 4, there is actually more than 30.000 users using the front end every day.
Second it clearly state the it's the first discovery for EDSM flight logs.
Third, you can blame Frontier for not providing API support to console, there is nothing we can do about it.

For deletion, as you wish, post on the galactic map topic and the team in charge will gladly remove what you want.

**Comment by Gonsan78** [comment] 2018-06-13 14:48
I still do not find where it says that only first discoveries can be
awarded to those CMDRs that can import their flight log. As well as I do
not find any flight log of the user that has "adjudged" the discovery with
my photos and my description.
I'm not being tough or aggressive. I simply say that the information you
are giving (if you prefer the 30,000) is not true. and, as you are
confirming, you deceive anyone who enters the web to be able to fill it
with content.

Thanks for cheating me. Keep the good work
​ 👍

**Comment by AnthorNet** [comment] 2018-06-13 15:01
It has always been the case, EDSM is use to store flight logs since the beginning.

Flight logs can be check on the commander profile, if it is public.

Nobody forced you to share your discovery for the galactic map as far as I know?

**Comment by Gonsan78** [comment] 2018-06-13 15:22
In the instructions to include new systems does not say anything about
Flight Logs. as much as the entire web was made for that. Review the
description of the FAQ's <https://www.edsm.net/en/faq>

It is a public profile that has not submit any distance, but has first
discovered 4,686 systems... (seriously?) As you can see here
<https://www.edsm.net/en/user/profile/id/23632/cmdr/D%C3%A6sglaar+%5BBSS%5D>

Evidently no one has forced me to share my discovery and when I did, I
thought it would be good for everyone. Not for others to wear the medal for
absurd technicalities of the game platform.
If I can not send the Log and can not probe the first discover. I think
it's right that the discover is given to another, but at least do not use
my description and my photos .. It's a very serious lack of respect.

Sorry about my poor English

Best Regards

**Comment by AnthorNet** [comment] 2018-06-13 16:47
4.000 systems discovered is nothing, our database holds more than 20 millions...

Anyway deleting, and closing.

**Closed as completed by AnthorNet** 2018-06-13 16:47 UTC

**Comment by Gonsan78** [comment] 2018-06-13 20:36
The lack of arguments is not sufficient reason to close the claim. You are
telling me that the first discovery of a system can only be achieved (from
PC exclusively apparently) by uploading the Flight Journal.
Well, that user who has the authorship of the system has not uploaded any
flight journal and has 5000 systems of first discovery ...  so...

As there are no more arguments to sustain this, you simply delete them and
go out? Perfect work...

**Comment by Gonsan78** [comment] 2018-06-13 20:37
Reopened #170 <https://github.com/EDSM-NET/FrontEnd/issues/170>.

**Comment by gregmcdougall** [comment] 2018-06-13 22:08
I think there's a language barrier here.

- EDSM is nothing to do with Elite "First Discovery" tags (based on who sells data to Universal Cartographics first). You may or may not have tags on Pyurks HC-J d10-18 - I can't view the system as I haven't visited it
- EDSM is nothing to do with Frontier Galactic Mapping project - you (and I) have uploaded POIs for consideration there, and we're free to do so whether we use EDSM or not (although I would imagine most do, as that's where the POIs will be recorded if accepted)
- The EDSM database records who first entered the system into EDSM "That system was first discovered for EDSM by..." as reported to EDSM (not the same as a Cmdr on any platform visiting the system)
- This works using programs like EDMC on PC/Mac to take the Logs from Elite and pass them into the database
- If we could get the data from PS4 / Xbox we would, but we can't
- EDSM is completely fair - if an EDSM user with several years of logs imports them wholesale, and they visited a system before the current EDSM user recorded, then the system page will reflect their name. This is unconnected with Elite (the game) - there are many thousands more systems with 'first discovered by' tags in the GalMap than are in EDSM (not everyone who plays is registered in EDSM)

**Comment by AnthorNet** [comment] 2018-06-14 07:01
I don't know where my arguments are insufficients...

The user you linked have 8.526 systems visited as of today, so obviously you missed something, you can see all his history here: https://www.edsm.net/en/user/flight-logs/id/23632/cmdr/D%C3%A6sglaar+%5BBSS%5D
If you go to page 71, you'll even see the visit to the system: https://www.edsm.net/en/user/flight-logs/id/23632/cmdr/D%C3%A6sglaar+%5BBSS%5D/index/p/71

![image](https://user-images.githubusercontent.com/654353/41396483-5c86c93e-6fb1-11e8-9b46-0650f7bf15b8.png)

Your entry was deleted simply because you asked for it to be deleted, so I'm sorry, but I'll will not reopen that issue.
Functionalities are working as intended and you request was fullfilled.
